accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'account'

urlpatterns = [
    path(r'_login/', auth_views.LoginView.as_view(), name='login'),
    path(r'_register/', views.register, name='register'),
    path(r'_logout/', auth_views.LogoutView.as_view(), name='logout'),
]

letters/urls.py
from django.urls import path

from letters import views

app_name = 'letters'

urlpatterns = [
    path(r'_explain/', views.explain, name='explain'),
    path(r'_compose/', views.compose, name='compose'),
    path(r'_success/', views.success, name='success'),
    path(r'_list', views.list_letters, name='list')
]

yearlify/urls.py
from django.contrib import admin
from django.urls import path, include

from yearlify import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),

    path('account', include(('accounts.urls', 'account'), namespace='account')),

    path('letters', include(('letters.urls', 'letters'), namespace='letters')),
]

accounts/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager
)

from django.db import models

class UserManager(BaseUserManager):
    def create_user(self, email, name, password=None, commit=True):

        user = self.model(
            email=self.normalize_email(email),
            name=name
        )
        user.set_password(password)

        if commit:
            user.save()

        return user

    def create_superuser(self, email, name, password):
        user = self.create_user(email, name, password, commit=False)
        user.is_staff = True
        user.is_superuser = True
        user.is_admin = True
        user.save()
        return user


class User(AbstractBaseUser):

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=100, blank=False)
    
    is_admin = models.BooleanField('admin status', default=False)
    is_staff = models.BooleanField('staff status', default=False)
    is_superuser = models.BooleanField('superuser status', default=False)
    is_active = models.BooleanField('active', default=True)
    
    date_joined = models.DateTimeField(auto_now=True, blank=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin
  
    def has_module_perms(self, app_label):
        return True

letters/models.py
from django.db import models

from accounts.models import User
from yearlify.settings import EMAIL_HOST_USER
from django.core.mail import send_mail

from django_cryptography.fields import encrypt
import datetime

class Letter(models.Model):
    user = models.ForeignKey(User, related_name='user_letter', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now=True)
    send_on = models.DateField(null=True, blank=False)

    content = encrypt(models.TextField())

    def __str__(self):
        return "Letter by {0} created on {1}".format(self.user.email, self.created_at.strftime('%D'))

    def process(self):
        subject = "Yearlify letter for {0}".format(self.user.name)
        message = self.content 
        send_mail(subject, message, EMAIL_HOST_USER, [self.user.email], fail_silently = False)

    @classmethod
    def process_all(cls):
        for letter in cls.objects.all():
            if letter.send_on == datetime.today().date():
                letter.process()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'name', 
            'email', 
            'password1',
            'password2',
            ]
        labels = {
            'name': 'What is your name?',
            'email': 'What email should we use to contact you (only once a year)?',
            'password1': 'Password',
            'password2': 'Confirm Password'
        }

letters/forms.py
from django.forms import ModelForm
from django import forms

from .models import (
    Letter
)

class LetterForm(ModelForm):

    content = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Letter
        fields = [
            'content'
            ]
        labels = {
            'content' : ""
            }

accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

from .forms import RegisterForm

def register(request):
    
    if request.method == 'POST':
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('letters:compose')
    else:
        form = RegisterForm(request.POST or None)

    context = {
        'form': form
    }

    return render(request, 'registration/register.html', context=context)

letters/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .models import (
    Letter
    )
from .forms import (
    LetterForm
    )

from accounts.models import User

import datetime

def explain(request):
    return render(request, 'explain.html', context={})

@login_required
def compose(request):
    form = LetterForm(request.POST or None)
    
    if request.method == 'POST':
        if form.is_valid():

            due_date = datetime.date(2021, 12, 30)

            new_letter = Letter(
                user=request.user,
                content=form.cleaned_data['content'],
                send_on=due_date, 
            )
            new_letter.save()
            return redirect('letters:success')

    context = {
        'form': form
    }
    return render(request, 'compose.html', context=context)

@login_required
def success(request):
    return render(request, 'success.html', context={})

@login_required
def list_letters(request):
    letters = Letter.objects.filter(user=request.user).all()
    context = {
        'letters': letters
    }
    return render(request, 'list.html', context=context)

yearlify/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html', context={})

letters/templates/compose.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<p>Paste your letter here - we're trying to build the website so you can write the letter in your browser, but it's still a work in progress. We have to make due with this for now - sorry!</p>
<p>The letter can be as long (or short!) as you want.</p>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-outline-dark">Save</button>
</form>
{% endblock %}

letters/templates/explain.html
{% extends 'base.html' %}

{% block content %}

<div class="text-box">

  <p class="bold-text">Before we begin, a bit of an explanation about what we’re doing. The process will be very simple, there’s really only three steps to it:</p>
  
  <div class="bullet-point">
    <ul>
      <li>Creating a user, so we can get your contact information and email you when the time comes</li>
      <li>Creating the letter itself</li>
      <li>Living your life, maybe even forgetting about this and getting an email in about a year’s time with the letter</li>  
    </ul>
  </div>

  <p class="bold-text">There’s also a couple of things that are important to keep in mind about this service:</p>  

  <div class="bullet-point">
    <ul>
      <li>The text you write or upload is encrypted so it remains private and no one can read it (not even the developer), so you can rest assured that your privacy is taken good care of</li>
      <li>This is very new, so if you want to send feedback we’ll be very grateful. At the end of the process you'll see a confirmation page with an email you can send us to provide feedback</li>
    </ul>  
  </div>

  <p class="bold-text">Does that all make sense? Happy? If you want to get started, click next to continue</p>
</div>

<a href="{% url 'account:register' %}" class="btn btn-outline-dark">Next</a>

{% endblock %}

letters/templates/list.html
{% extends 'base.html' %}

{% block content %}

{% if letters %}
{% for letter in letters %}
<p>- Letter created on {{ letter.created_at }} due to be sent on {{ letter.send_on }} -</p>
<br>
{% endfor %}
{% else %}
<p>No letter for this year. Want to write one? <a href="{% url 'letters:compose' %}">Write it here</a></p>
{% endif %}
{% endblock %}

letters/templates/success.html
{% extends 'base.html' %}

{% block content %}

<p>Thanks, {{ request.user.name }}. If you're seeing this, it means it all worked fine. There's nothing else you need to do now other than wait. You can check your letter shedule now that you're logged in, but nothing else will happen until we send you the letter at the end of the year.</p>

<p>Share this site with whoever you think will like it. Email <a href="mailto:tasa@enriquetasa.com">tasa@enriquetasa.com</a> if you have any feedback. Click <a href="https://github.com/enriquetasa/yearlify">here</a> to access the website's source code.</p>
  
<p>See you next year!</p>

<a href="{% url 'home' %}" class="btn btn-secondary">Go home</a>

{% endblock %}

templates/base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Yearlify</title>
  <meta name="author" content="Enrique Tasa">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  
  {% load static %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <style>
    body {
      background-color: linen;
      text-align: center;
      min-height: 75rem;
      padding-top: 4.5rem;
    }
    .text-box {
      margin-left: 20%;
      margin-right: 20%;
      text-align: center;
    }
    .bullet-point{
      text-align: justify;
      margin-left: 23%;
      margin-right: 23%;
    }
    .asteriskField {
      display: none;
    }
    #hint_id_password2 {
         display: none;
     }
    .bold-text {
      font-weight: bold;
    }
    </style>
<!-- TODO - this is a hacky way of suppresing form elements, make sure to change it-->
</head> 

<main class="container">
    {% block content %}
    {% endblock %}
  </main>

{% include 'footer.html' %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<style type="text/css">
  .fixed-bottom {
    position: fixed;
    bottom: 0;
    width: 100%;
    text-align: center;
  }
  .centered-small-text {
    display: inline-block;
    text-size-adjust: 50%;
    padding-left: 30px;
    
  }
  a {
    color: grey;
  }
</style>

<footer class="footer mt-auto py-3 fixed-bottom" style="background-color: linen;">
  <div class="container" style="padding: 0 15px">
    {% if request.user.is_authenticated %}
    <span class="text-muted centered-small-text"><a href="{% url 'letters:list' %}">your schedule</a></span>
    <span class="text-muted centered-small-text"><a href="{% url 'account:logout' %}">logout</a></span>
    {% else %}
    <span class="text-muted centered-small-text"><a href="{% url 'account:login' %}">login</a></span>
    {% endif %}
    <span class="text-muted centered-small-text"><a href="{% url 'home' %}">home</a></span>
  </div>
</footer>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to Yearlify!</h1>

<p>The aim of this site is to guide you through an exercise to review on the past year and plan for the next. If you choose to partake, you’ll write a letter to your future self - and we’ll send you an email at the end of the year so you can review it and reflect on it</p>

{% if not request.user.is_authenticated %}
<p>Are you new?</p>
<a href="{% url 'letters:explain' %}" class="btn btn-secondary">Register</a>
<br>
<br>
<p>If you already have an account,</p>
<a href="{% url 'letters:list' %}" class="btn btn-outline-dark">Login</a>
{% else %}
<a href="{% url 'letters:list' %}" class="btn btn-secondary">See your letter schedule</a>
{% endif %}
{% endblock %}